#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER dagster WITH PASSWORD 'dagster';
  CREATE DATABASE dagster WITH OWNER = dagster;
  \c dagster
  GRANT CONNECT ON DATABASE dagster TO dagster;
  GRANT ALL PRIVILEGES ON DATABASE dagster TO "$POSTGRES_USER";
  ALTER DEFAULT PRIVILEGES FOR ROLE dagster IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO "$POSTGRES_USER";
  ALTER DEFAULT PRIVILEGES FOR ROLE dagster IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO "$POSTGRES_USER";
  ALTER DEFAULT PRIVILEGES FOR ROLE dagster IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO "$POSTGRES_USER";

  CREATE DATABASE data_warehouse;
  GRANT ALL PRIVILEGES ON DATABASE data_warehouse TO "$POSTGRES_USER";

  CREATE DATABASE data_mart;
  GRANT ALL PRIVILEGES ON DATABASE data_mart TO "$POSTGRES_USER";

  CREATE DATABASE staging;
  GRANT ALL PRIVILEGES ON DATABASE staging TO "$POSTGRES_USER";
EOSQL