services:
  # Database
  postgres:
    image: postgres:17
    hostname: postgres
    env_file: .env
    networks:
      - traffy-troffi
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # S3-compatible object storage
  garage:
    image: dxflrs/garage:v0.9.3
    restart: unless-stopped
    networks:
      - traffy-troffi
    environment:
      - GARAGE_ADMIN_TOKEN=${GARAGE_ADMIN_TOKEN:-traffy_troffi}
    ports:
      - "3900:3900"
      - "3901:3901"
    volumes:
      - ./docker/garage/garage.toml:/etc/garage.toml
      - traffy-s3-meta:/var/lib/garage/meta
      - traffy-s3-data:/var/lib/garage/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3902/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Spark master
  spark-master:
    image: bitnami/spark:3.5.0
    hostname: spark-master
    networks:
      - traffy-troffi
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - spark-data:/bitnami/spark

  # Spark worker
  spark-worker:
    image: bitnami/spark:3.5.0
    hostname: spark-worker
    networks:
      - traffy-troffi
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8081"
    volumes:
      - spark-data:/bitnami/spark
    depends_on:
      - spark-master

#  # Dagster orchestration
#  dagster-webserver:
#    build:
#      context: ./docker/dagster
#      dockerfile: Dockerfile
#      labels:
#        - traffy-troffi-dagster
#    networks:
#      - traffy-troffi
#    entrypoint:
#      - dagster-webserver
#      - -h
#      - "0.0.0.0"
#      - -p
#      - "3000"
#      - -w
#      - workspace.yaml
#    ports:
#      - "3000:3000"
#    environment:
#      - DAGSTER_POSTGRES_HOST=postgres
#      - DAGSTER_POSTGRES_PORT=5432
#      - DAGSTER_POSTGRES_DB=dagster
#      - DAGSTER_POSTGRES_USER=dagster
#      - DAGSTER_POSTGRES_PASSWORD=dagster
#      - S3_ENDPOINT=http://garage:3900
#      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-traffy_access}
#      - S3_SECRET_KEY=${S3_SECRET_KEY:-traffy_secret}
#      - SPARK_MASTER_URL=spark://spark-master:7077
#    volumes:
#      - ./docker/dagster/workspace.yaml:/dagster/workspace.yaml
#      - ./docker/dagster/dagster.yaml:/dagster/dagster.yaml
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - postgres
#      - garage
#      - spark-master
#      - dagster-code
#
#  # Dagster daemon for schedule and sensor execution
#  dagster-daemon:
#    build:
#      context: ./docker/dagster
#      dockerfile: Dockerfile
#      labels:
#        - traffy-troffi-dagster
#    entrypoint:
#      - dagster-daemon
#      - run
#    networks:
#      - traffy-troffi
#    environment:
#      - DAGSTER_POSTGRES_HOST=postgres
#      - DAGSTER_POSTGRES_PORT=5432
#      - DAGSTER_POSTGRES_DB=dagster
#      - DAGSTER_POSTGRES_USER=dagster
#      - DAGSTER_POSTGRES_PASSWORD=dagster
#      - S3_ENDPOINT=http://garage:3900
#      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-traffy_access}
#      - S3_SECRET_KEY=${S3_SECRET_KEY:-traffy_secret}
#      - SPARK_MASTER_URL=spark://spark-master:7077
#    volumes:
#      - ./docker/dagster/workspace.yaml:/dagster/workspace.yaml
#      - ./docker/dagster/dagster.yaml:/dagster/dagster.yaml
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - postgres
#      - garage
#      - spark-master
#
#  dagster-code:
#    build:
#      context: ./docker/dagster
#      dockerfile: Dockerfile
#      labels:
#        - traffy-troffi-dagster-code
#    networks:
#      - traffy-troffi
#    entrypoint:
#      - dagster
#      - code-server
#      - start
#      - "-h"
#      - "0.0.0.0"
#      - "-p"
#      - "4000"
#      - "-m"
#      - "traffy-troffi.dagster"
#    environment:
#      - DAGSTER_POSTGRES_HOST=postgres
#      - DAGSTER_POSTGRES_PORT=5432
#      - DAGSTER_POSTGRES_DB=dagster
#      - DAGSTER_POSTGRES_USER=dagster
#      - DAGSTER_POSTGRES_PASSWORD=dagster
#      - S3_ENDPOINT=http://garage:3900
#      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-traffy_access}
#      - S3_SECRET_KEY=${S3_SECRET_KEY:-traffy_secret}
#      - SPARK_MASTER_URL=spark://spark-master:7077
#    volumes:
#      - ./traffy-troffi:/dagster/traffy-troffi
#      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres-data:
  traffy-s3-data:
  traffy-s3-meta:
  spark-data:

networks:
  traffy-troffi:
    name: traffy-troffi